# Generated by Django 5.2.4 on 2025-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeproposal",
            name="status",
            field=models.CharField(
                choices=[("A", "Ожидает"), ("T", "Принята"), ("R", "Отклонена")],
                default="A",
                max_length=1,
                verbose_name="Статус сделки",
            ),
        ),
    ]
